ALTER TABLE moods 
  ALTER COLUMN mood_level SET NOT NULL,
  ALTER COLUMN feelings SET NOT NULL,
  ALTER COLUMN journal SET NOT NULL,
  ALTER COLUMN sleep_hours SET NOT NULL,
  ALTER COLUMN created_at SET NOT NULL;
